# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: myob-essentials-api 0.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "myob-essentials-api"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["BrunoChauvet"]
  s.date = "2015-01-22"
  s.description = "TODO: longer description of your gem"
  s.email = "bruno.chauvet@maestrano.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/myob-essentials-api.rb",
    "lib/myob/essentials/api/client.rb",
    "lib/myob/essentials/api/helper.rb",
    "lib/myob/essentials/api/model/base.rb",
    "lib/myob/essentials/api/model/business.rb",
    "lib/myob/essentials/api/model/contact.rb",
    "lib/myob/essentials/api/model/inventory_item.rb",
    "myob-essentials-api.gemspec",
    "spec/fixtures/businesses.json",
    "spec/fixtures/businesses/168254.json",
    "spec/fixtures/businesses/168254/contacts.json",
    "spec/fixtures/businesses/168254/contacts/3604150.json",
    "spec/fixtures/businesses/168254/inventory/items.json",
    "spec/fixtures/businesses/168254/inventory/items/987816.json",
    "spec/myob/essentials/api/client_spec.rb",
    "spec/myob/essentials/api/model/business_spec.rb",
    "spec/myob/essentials/api/model/contact_spec.rb",
    "spec/myob/essentials/api/model/inventory_item_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/BrunoChauvet/myob-essentials-api"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5"
  s.summary = "TODO: one-line summary of your gem"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<oauth2>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<oauth2>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<oauth2>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

